export const browserCoreExamples = [
  "openpaw browser status",
  "openpaw browser start",
  "openpaw browser stop",
  "openpaw browser tabs",
  "openpaw browser open https://example.com",
  "openpaw browser focus abcd1234",
  "openpaw browser close abcd1234",
  "openpaw browser screenshot",
  "openpaw browser screenshot --full-page",
  "openpaw browser screenshot --ref 12",
  "openpaw browser snapshot",
  "openpaw browser snapshot --format aria --limit 200",
  "openpaw browser snapshot --efficient",
  "openpaw browser snapshot --labels",
];

export const browserActionExamples = [
  "openpaw browser navigate https://example.com",
  "openpaw browser resize 1280 720",
  "openpaw browser click 12 --double",
  'openpaw browser type 23 "hello" --submit',
  "openpaw browser press Enter",
  "openpaw browser hover 44",
  "openpaw browser drag 10 11",
  "openpaw browser select 9 OptionA OptionB",
  "openpaw browser upload /tmp/file.pdf",
  'openpaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openpaw browser dialog --accept",
  'openpaw browser wait --text "Done"',
  "openpaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openpaw browser console --level error",
  "openpaw browser pdf",
];
